kind: Service
apiVersion: v1
metadata:
  name: elastic
  namespace: logs
  labels:
    app: elastic
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: transport
      protocol: TCP
      port: 9300
      targetPort: 9300
  selector:
    app: elastic
  type: ClusterIP
  
