kind: Service
apiVersion: v1
metadata:
  name: kibana
  namespace: logs
  labels:
    app: kibana
spec:
  ports:
    - name: transport
      protocol: TCP
      targetPort: 5601
      port: 5601
      nodePort: 30020
  selector:
    app: kibana
  type: NodePort
  
