kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv-002
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/shlomo/mongo/data2"